### ISSUE TITLE
How to handle disqus for "next episode"

### ISSUE THREAD

**Issue by veggiemonk** [devsecopstalks/website#11]
We would like to have the previous workflow for handling "next episode".

I have no idea how to do with disqus/hugo

**Comment by Andrey9kin** [comment]
@veggiemonk I will research later on

**Comment by veggiemonk** [comment]
The "next episode" discussion will be handled by Gitter https://gitter.im/devsecopstalks/community

**Comment by Andrey9kin** [comment]
dropped the next episode thingy and added link to Gitter community to the home page
