### ISSUE TITLE
Add podcast networks badges to the website 

### ISSUE THREAD

**Issue by Andrey9kin** [devsecopstalks/website#12]
See security now for example https://twit.tv/shows/security-now

**Comment by veggiemonk** [comment]
Can someone post the URL for all the platforms the podcast is available? I lost track....

**Comment by Andrey9kin** [comment]
Apple podcast https://podcasts.apple.com/se/podcast/the-devsecops-talks-podcast/id1503645730
Spotify https://open.spotify.com/show/4tGYslKaJU9d8Fg3Qf9gaO
Google podcast https://podcasts.google.com/feed/aHR0cHM6Ly9mZWVkLnBvZGJlYW4uY29tL2RldnNlY29wcy9mZWVkLnhtbA==
