### ISSUE TITLE
getsturdy with Kirill

### ISSUE THREAD

**Issue by Andrey9kin** [devsecopstalks/website#36]
we are going to talk with Kirill about https://getsturdy.com and why he thinks it is a right time for the new SCM

**Comment by Andrey9kin** [comment]
Please post your ideas and questions here, we could also collect links and notes during the show in this issue so it is easier when we do publishing

**Comment by Andrey9kin** [comment]
also, do you homework and try the tool

**Comment by Andrey9kin** [comment]
Perhaps @RandomSort would be interested in joining?

**Comment by RandomSort** [comment]
Hi, if you have not done this yet, I would be happy to join for an hour or
so.

Sound like a good topic, and I believe they have some interesting points.

**Comment by Andrey9kin** [comment]
@RandomSort this one is done but we should do a follow-up next year!
