### ISSUE TITLE
Prometheus and monitoring

### ISSUE THREAD

**Issue by Andrey9kin** [devsecopstalks/website#43]

**Comment by Andrey9kin** [comment]
@nvkv do you want to join for this one?

**Comment by Andrey9kin** [comment]
Also, would be good to touch open telemetry

**Comment by nvkv** [comment]
This is the first time I'll actually consider invitation for some reason.
When do you plan to record it?

**Comment by Andrey9kin** [comment]
@nvkv timing is flexible. We are going to talk about AWS going down next week (16th) which means that the next recording is supposed to happen in two weeks, i.e. 30th but I don't think it will. Probably sometime in January. How about January 13th?

**Comment by nvkv** [comment]
That looks doable, but I can be on the move at this time, let's return to this conversation at the end of December then.
Thanks for the invitation btw :)

**Comment by Andrey9kin** [comment]
@mattiashem can you get in touch with Semyon and preliminary book him for 13th? Or perhaps you can take his email from github commits?
